import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import TanstackProvider from "@/components/TanstackProvider";

export const metadata: Metadata = {
  title: "Product Viewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{ boxSizing: "border-box", padding: "0", margin: "0" }}
    >
      <body
        style={{
          maxWidth: "100vw",
          overflowX: "hidden",
          color: "var(--foreground)",
          background: "var(--background)",
          fontFamily: "Arial, Helvetica, sans-serif",
          WebkitFontSmoothing: "antialiased",
          MozOsxFontSmoothing: "grayscale",
        }}
      >
        <TanstackProvider>
          <Header />
          {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
