import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import TanstackProvider from "@/components/TanstackProvider";

export const metadata: Metadata = {
  title: "Product Viewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <Header />
          {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
